# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FootNet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootNet
  pod 'CocoaLumberjack/Swift' #Logger
  pod 'Material', '~> 2.16.4'

  target 'FootNetTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
