# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'FootNet' do
  
  # Pods for FootNet
  pod 'CocoaLumberjack/Swift' #Logger
  pod 'Material', '~> 2.16.4'
  
  target 'FootNetTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'CocoaLumberjack/Swift' #Logger
    pod 'Material', '~> 2.16.4'
  end

  target 'FootNetUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'CocoaLumberjack/Swift' #Logger
    pod 'Material', '~> 2.16.4'
  end

end
